version: '3.8'

services:
  ml-server:
    image: ecg-whisperx:v44
    container_name: ecg-ml-server
    ports:
      - "8080:8080"
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - HF_TOKEN=${HF_TOKEN:-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}
      - FASTAPI_BASE_URL=${FASTAPI_BASE_URL:-https://ho-it.site}
      # AWS 자격 증명 환경변수
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME:-ecg-audio-analyzer-production-audio-084828586938}
    volumes:
      - ./output:/app/output
      - ./friends.mp4:/app/friends.mp4:ro
      - /tmp:/tmp
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s