name: ecg-ml
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.9

  # Web Framework (버전 지정)
  - fastapi>=0.100.0
  - uvicorn>=0.23.0
  - requests>=2.31.0

  # Audio Processing (버전 지정)
  - librosa>=0.10.0
  - pysoundfile>=0.12.0
  - ffmpeg
  - sox
  - libsndfile

  # ML Framework (CUDA, 버전 지정)
  - pytorch>=2.0.0
  - torchvision
  - torchaudio>=2.0.0
  - pytorch-cuda=11.8

  # AWS & Utilities (버전 지정)
  - boto3>=1.26.0
  - psutil>=5.9.0
  - aiofiles>=23.1.0

  # Data Processing (버전 지정)
  - numpy>=1.24.0
  - pydantic>=2.0.0

  # Logging & Config (버전 지정)
  - structlog>=23.1.0
  - python-dotenv>=1.0.0

  # pip 전용 패키지 (requirements.txt 버전 반영)
  - pip
  - pip:
      - whisperx
      - pyannote-audio>=3.0.0
      - yt-dlp>=2023.7.6
      - ffmpeg-python>=0.2.0
