# ECG Audio Analyzer ML Server Configuration

# Development tools configuration
[tool.black]
line-length = 88
target-version = ['py39']
include = '\.pyi?$'

[tool.ruff]
target-version = "py39"
line-length = 88
exclude = ["ml_api_server.py"]

[tool.ruff.lint]
# Allow E402 for the main ML server file due to sys.path manipulation
ignore = ["E722"]  # Allow bare except for error handling

[tool.ruff.lint.per-file-ignores]
"ml_api_server.py" = ["E402"]
"src/__init__.py" = ["E722"]
"src/api.py" = ["E722", "F841"]
"src/models/model_manager.py" = ["F841"]
"src/services/audio_extractor.py" = ["E722"]
"src/utils/aws_utils.py" = ["E722"]
"src/utils/logger.py" = ["F841"]

[tool.bandit]
# Skip certain security warnings that are acceptable in this context
skips = [
    "B110",  # Try/Except/Pass - acceptable for graceful error handling
    "B404",  # subprocess import - necessary for ffmpeg integration
    "B603",  # subprocess without shell=True - safe with controlled input
    "B112",  # Try/Except/Continue - acceptable for iteration error handling
]

# Exclude certain files from security scanning
exclude_dirs = ["build", "dist", ".git", "__pycache__"]
